### ISSUE TITLE
EPIC - Add theme support to UI components and improve user experience with themes

### ISSUE THREAD

**Issue by handreyrc** [apache/incubator-kie-tools#2219]
- [ ] https://github.com/apache/incubator-kie-tools/issues/2214
- [ ] https://github.com/apache/incubator-kie-tools/issues/2215
- [ ] https://github.com/apache/incubator-kie-tools/issues/2216
- [ ] https://github.com/apache/incubator-kie-tools/issues/2217
- [ ] https://github.com/apache/incubator-kie-tools/issues/2218
