### ISSUE TITLE
Move SLWT quarkus-accelerator into kie-tools as a new package serverless-logic-web-tools-accelerator-quarkus

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2769]
Move the `quarkus-accelerator` branch from the [Serverless Logic Sandbox Deployment repository](https://github.com/kubesmarts/sandbox-deployment/tree/quarkus-accelerator) into the `kie-tools` repository as a new package named `serverless-logic-web-tools-accelerator-quarkus`.

**Tasks:**
- [ ] Move `quarkus-accelerator` to the new package
- [ ] Extract the HTTP server for Git bare repositories into a separate package (`@kie-tools/git-bare-repo-via-http-dev-server`).
- [ ] Setup daily-dev (https://ci-builds.apache.org/job/KIE/job/kie-tools/job/main/job/kie-tools-daily-dev-publish/) to push the `incubator-kie-serverless-logic-web-tools-accelerator-quarkus`'s `main` branch correctly.
- [ ] Update SLWT references to the new Apache repository

**Comment by fantonangeli** [comment]
I close this issue because serverless-logic-web-tools has been removed from this repo
