### ISSUE TITLE
Migrate `kie-samples` to `kie-tools` as a new package `serverless-logic-web-tools-samples`

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-tools#2770]
Move the **`kie-samples`** repository (currently on  [kubesmarts/sandbox-catalog](https://github.com/kubesmarts/sandbox-catalog)) to the `kie-tools` repository as a new package named `serverless-logic-web-tools-samples`.

**Tasks:**
- [ ] Move the contents of `kie-samples` to a new package `serverless-logic-web-tools-samples`.
- [ ] Replicate the GH Workflows [combine-sample-definitions.yml](https://github.com/kiegroup/kie-samples/blob/main/.github/workflows/combine-sample-definitions.yml) and [sample-validation.yml](https://github.com/kiegroup/kie-samples/blob/main/.github/workflows/sample-validation.yml) using `pacakge.json` scripts
- [ ] Setup daily-dev (https://ci-builds.apache.org/job/KIE/job/kie-tools/job/main/job/kie-tools-daily-dev-publish/) to push the `incubator-kie-serverless-logic-web-tools-samples`'s `main` branch correctly.
- [ ] Update SLWT references to the new Apache repository

**Comment by fantonangeli** [comment]
Closing as SWF/SonataFlow has been removed in 10.3.x
