### ISSUE TITLE
EPIC - Persistence Enhancements - Q4 Milestone

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-tools#2934]
### Description

Placeholder EPIC for persistence enhancements in the SonataFlow operator:

- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/437
- [ ] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/522
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/516
- [x] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/506
- [ ] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/524
- [ ] https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/497
- [x] https://github.com/apache/incubator-kie-tools/issues/2659

**Comment by rhkp** [comment]
FYI - Myself @rhkp is working on this item.

**Comment by tiagobento** [comment]
Closing due to https://github.com/apache/incubator-kie-tools/pull/3540
