### ISSUE TITLE
EPIC - Resizing of BeeTable and DMN Editor's Boxed Expression Editor

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-tools#3812]
- [ ] https://github.com/kiegroup/kie-issues/issues/180
- [ ] https://github.com/kiegroup/kie-issues/issues/178
- [ ] https://github.com/kiegroup/kie-issues/issues/181
- [ ] https://github.com/kiegroup/kie-issues/issues/188
- [ ] https://github.com/kiegroup/kie-issues/issues/197
- [ ] https://github.com/kiegroup/kie-issues/issues/199
- [ ] https://github.com/kiegroup/kie-issues/issues/200
- [ ] https://github.com/kiegroup/kie-issues/issues/179
- [ ] https://github.com/kiegroup/kie-issues/issues/198
- [ ] https://github.com/kiegroup/kie-issues/issues/534
- [ ] https://github.com/kiegroup/kie-issues/issues/535
