### ISSUE TITLE
EPIC - The new React-based SceSim Editor!

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-tools#3813]
### Tasks 1th Phase
- [x] https://github.com/kiegroup/kie-issues/issues/384
- [x] https://github.com/kiegroup/kie-issues/issues/385
- [x] https://github.com/kiegroup/kie-issues/issues/538
- [x] https://github.com/kiegroup/kie-issues/issues/523
- [x] https://github.com/kiegroup/kie-issues/issues/561
- [x] https://github.com/kiegroup/kie-issues/issues/580
- [x] apache/incubator-kie-issues#629 
- [x] apache/incubator-kie-issues#665
- [x] apache/incubator-kie-issues#737
- [x] apache/incubator-kie-issues#738
- [x] apache/incubator-kie-issues#1463
- [x] apache/incubator-kie-issues#1511
- [x] apache/incubator-kie-issues#1481
- [x] apache/incubator-kie-issues#970
- [x] apache/incubator-kie-issues#1514
- [x] apache/incubator-kie-issues#1552
- [x] apache/incubator-kie-issues#1844

### Known Issues

- [x] apache/incubator-kie-issues#1855
- [x] apache/incubator-kie-issues#1353
- [x] apache/incubator-kie-issues#1807
- [x] apache/incubator-kie-issues#1808
- [ ] apache/incubator-kie-tools#3935 
- [x] apache/incubator-kie-issues#1810 
- [x] apache/incubator-kie-issues#1870
- [x] apache/incubator-kie-issues#1871
- [x] apache/incubator-kie-issues#1875 
- [x] apache/incubator-kie-issues#1879 
- [x] apache/incubator-kie-issues#1919

### Tasks 2th Phase
- [ ] Test Scenario Editor: Collections management
- [ ] The BeeTable data cells should be able to contain placeholder values
- [ ] Shouldn't be possible to assign data to Undefined columns (eg. INSTANCE-1 / PROPERTY-1 columns)
- [ ] apache/incubator-kie-tools#3896 
- [ ] apache/incubator-kie-tools#3929
- [ ] apache/incubator-kie-tools#3930
- [ ] apache/incubator-kie-tools#3931
 - [ ] apache/incubator-kie-tools#3932
- [ ] apache/incubator-kie-tools#3895
- [ ] apache/incubator-kie-tools#3936
- [ ] apache/incubator-kie-tools#3937
