### ISSUE TITLE
EPIC - Move the source of `kie-sandbox-quarkus-accelerator` to `kie-tools` and use its repo as a deployment repo

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-tools#3886]
Instead of maintaining the code directly on https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator, we should just move the code to a package on `kie-tools` and push it to https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator as part of the release process. This will make sure this repo is always in sync with the rest of `kie-tools`.

Locally, when developing KIE Sandbox, we should spawn a Git server so that KIE Sandbox can clone the Accelerator code from it.

> **NOTE**: We can do the same for https://github.com/kiegroup/serverless-logic-sandbox-deployment/tree/quarkus-accelerator and https://github.com/kiegroup/kie-samples

---

TODO:
- [x] Bring the code to `kie-tools` as a new package (`packages/kie-sandbox-accelerator-quarkus`)
- [x] Delete old branches (`template`, `0.0.0`, and `10.0.999`) from https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator
- [x] Convert KIE Sandbox Quarkus Accelerator repo to "Template" on GitHub (https://issues.apache.org/jira/browse/INFRA-26307)
- [x] Make sure https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator 's description contains up-to-date information about the repo's "automatic updates" nature.
- [ ] Make sure `main`'s `daily-dev` (https://ci-builds.apache.org/job/KIE/job/kie-tools/job/main/job/kie-tools-daily-dev-publish/) is publishing to the `main` branch correctly.
- [ ] Make sure `10.0.x`'s `weekly` (https://ci-builds.apache.org/job/KIE/job/kie-tools/job/10.0.x/job/kie-tools-weekly-publish/) is publishing to the `10.0.x` branch correctly.
- [ ] Make sure release jobs are properly updated for producing Release Candidate artifacts based on `packages/kie-sandbox-accelerator-quarkus`
- [ ] Make sure release jobs are properly updated for pushing tags based on Release Candidate artifact (apache-kie-incubator-{version}-sandbox-accelerator-quarkus.zip)

**Comment by tiagobento** [comment]
For Apache KIE 10.0, we'll still rely on manually editing code on https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator/tree/0.0.0, but for 10.1 and beyond, we'll produce the source of the Accelerator from `kie-tools`, and we'll treat it as a release artifact. https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator will become a hosting repo only (no development), just like https://github.com/apache/incubator-kie-kogito-online hosts the GitHub Pages deployment of KIE Sandbox.

**Comment by tiagobento** [comment]
Our daily-dev builds should continue updating the 0.0.0 branch, although I think it would be better to switch for `main` instead, to follow the "streams" we have setup for container images too...

**Comment by tiagobento** [comment]
Added a TODO list in the description of this issues.
