### ISSUE TITLE
EPIC - Action plan of strategy for implementing the E2E test suite for the new DMN Editor

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-tools#3916]
This epic collects the action plan defined on the [strategy for implementing the E2E test suite for the new DMN Editor](https://github.com/apache/incubator-kie-issues/issues/874).

## Phases
1. https://github.com/apache/incubator-kie-tools/issues/3906
2. https://github.com/apache/incubator-kie-tools/issues/3905
3. https://github.com/apache/incubator-kie-tools/issues/3904

## Test cases

During the phases, we have to create tests to cover functionalities and non-functionalities of the new DMN editor, and here we collect the scenarios to be covered on the test suite:

### Editor Functionalities
- [ ] autolayout
- [ ] boxed expression
- [ ] data types (https://github.com/apache/incubator-kie-tools/issues/3950)
  - [ ] creation
  - [ ] deletion
  - [ ] structure
  - [ ] collection
  - [ ] constraint
- [ ] diagram
    - [x] `Add node`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Add connected node`
      - https://github.com/apache/incubator-kie-tools/pull/2158
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Add edge`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Add edge waypoint`
      - https://github.com/apache/incubator-kie-tools/pull/2189
      - https://github.com/apache/incubator-kie-tools/pull/2211
    - [x] `Add standalone node`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Delete edge`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Delete edge waypoint`
      - https://github.com/apache/incubator-kie-tools/pull/2211
    - [x] `Delete node`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Rename node`
      - https://github.com/apache/incubator-kie-tools/pull/2189
    - [x] `Resize node`
      - https://github.com/apache/incubator-kie-tools/pull/2239
    - [x] `Decision Service`
      - [ ] `Add Decision to Decision Service`
      - [ ] `Delete Decision from Decision Service`
      - [ ] `Update Decision Service divider line`
  - [x] drd
    - `Add DRD`
    - `Add node from DRG`
  - [ ] selection
  - [ ] external nodes
- [ ] id randomizer
- [ ] included models
    - [ ] `Import model`
      - [ ] importing DMN on the same namespace
      - [ ] importing DMN on different namespace
      - [ ] pmml
    - [ ] `Delete import`
    - [ ] `Rename import`
- [ ] overlay panel
- [ ] properties panel
  - [ ] boxed expression
  - [x] bkm node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] decision node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] input data node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] knowledge source node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] decision service node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] group node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] text annotation node
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] global
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [x] multiple nodes
    - https://github.com/apache/incubator-kie-tools/pull/2239
  - [ ] unkown node

### Editor Non functionalities
- [ ] re-renders
  - [ ] `store`

### Editor envelope
- [ ] svg
- [ ] drdIndex integrity (https://github.com/apache/incubator-kie-issues/issues/1174)
- [ ] keyboard shortcuts (https://github.com/apache/incubator-kie-tools/issues/3925)
  - [ ] cancel action (Escape)
  - [ ] create group (G)
  - [ ] copy node (Ctrl/Cmd + C)
  - [ ] cut node (Ctrl/Cmd + X
  - [ ] delete node (Delete/Backspace)
  - [ ] focus on selection (B)
  - [ ] hide from DRD (X)
  - [ ] horizontal navigation (Hold Shift)
  - [ ] move (Up/Down/Left/Right/Shift + Up/Shift + Down/Shift + Left/Shift + Right)
  - [ ] pan (Hold Alt)
  - [ ] paste node (Ctrl/Cmd + V)
  - [ ] redo (Ctrl/Cmd + Shift + Z)
  - [ ] reset position to origin (Space)
  - [ ] select/deselect all (A)
  - [ ] toggle hierarchy highlight (H)
  - [ ] toggle properties panel (I)
  - [ ] undo (Ctrl/Cmd + Z)
  - [ ] zoom (Hold Ctrl)
